spring.application.name=ChatTech-with-Virtual-Assistant
spring.profiles.active=dev

# La aplicación usa MongoDB para guardar el historial del chat.
spring.data.mongodb.uri=mongodb://localhost:27017/chattech